redis1:
    command: "redis-server --port 16380"
    image: redis 
    ports:
        - "16380:16380"

redis2:
    command: "redis-server --port 6381"
    image: redis 
    ports:
        - "6381:6381"

redis3:
    command: "redis-server --port 6382"
    image: redis 
    ports:
        - "6382:6382"

redis4:
    command: "redis-server --port 6383"
    image: redis 
    ports:
        - "6383:6383"

redis5:
    command: "redis-server --port 6384"
    image: redis 
    ports:
        - "6384:6384"

